APP_ANUNCIOS/IKLAN/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('', include('pwa.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

APP_ANUNCIOS/app/urls.py
from django.db import router
from django.urls import include, path
from .views import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('producto', ProductoViewset)
router.register('marca', MarcaViewset)

urlpatterns = [
    path('', home, name='home'),
    path('terminos/', terminos, name='terminos'),
    path('cat/<id>/', cat, name='cat'),
    path('agregar-producto/', agregar_producto, name='agregar_producto'),
    path('listar-producto/', listar_productos, name='listar_productos'),
    path('modificar-producto/<id>/', modificar_producto, name='modificar_producto'),
    path('eliminar-producto/<id>/', eliminar_producto, name='eliminar_producto'),
    path('registro/', registro, name='registro'),
    path('api/', include(router.urls)),
    path('error-facebook/', error_facebook, name="error_facebook"),
]

APP_ANUNCIOS/app/models.py
from django.db import models

# Create your models here.
class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre= models.CharField(max_length=50)
    username = models.CharField(max_length=100)
    precio= models.IntegerField(null=True)
    descripción = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField(auto_now=True)
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return self.nombre

APP_ANUNCIOS/app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import fields_for_model
from django.shortcuts import redirect
from .models import Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .validators import MaxSizeFilevalidator
from django.forms import ValidationError


class ProductoForm(forms.ModelForm): 

    nombre = forms.CharField(min_length=3, max_length=50)
    username = forms.CharField(min_length=3, max_length=100)
    imagen = forms.ImageField(required=False, validators=[MaxSizeFilevalidator(max_file_size=2)])
    precio = forms.IntegerField(required=False, min_value=1, max_value=115000000)


#    def clean_nombre(self):
#        nombre = self.cleaned_data["nombre"]
#        existe = Producto.objects.filter(nombre__iexact=nombre).exists()

        #if existe:
         #   raise ValidationError("Este nombre ya existe")
        #else:
         #   return nombre

    class Meta:
        model = Producto
        fields = ['nombre', 'username', 'precio', 'descripción', 'nuevo', 'marca', 'imagen']

        widgets = {
            "fecha_fabricacion": forms.SelectDateWidget()
        }

class CustomUserCreationFrom(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', "first_name", "last_name", "email", "password1","password2"]

APP_ANUNCIOS/app/views.py
from django.contrib.auth.password_validation import password_changed
from django.http.response import Http404
from django.shortcuts import get_object_or_404, render, redirect, get_list_or_404
from .models import Producto, Marca
from .forms import ProductoForm, CustomUserCreationFrom
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required
from rest_framework import serializers, viewsets
from .serializers import MarcaSerialize, ProductoSerializer
from django.contrib.auth.models import User
# Create your views here.

def error_facebook(request):
    return render(request, 'registration/error_facebook.html')

class MarcaViewset(viewsets.ModelViewSet):
    queryset= Marca.objects.all()
    serializer_class = MarcaSerialize

class ProductoViewset(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer

    def get_queryset(self):
        productos = Producto.objects.all()

        nombre = self.request.GET.get('nombre')
        
        if nombre:
            productos = productos.filter(nombre__contains=nombre)

        return productos

def home(request):
    productos = Producto.objects.all()
    categorias= Marca.objects.all()
    data ={
        'productos': productos,
        'categorias': categorias
    }
    return render(request, 'app/home.html', data)

def terminos(request):

    return render(request, 'app/terminos.html')

def cat(request, id):
    productos = Producto.objects.filter(marca=id)
    categorias= Marca.objects.all()
    data ={
        'productos': productos,
        'categorias': categorias
    }
    return render(request, 'app/cat.html', data)



#permiso para entrar a cualquier pesgtaña
#@login_required

def agregar_producto(request):
    data = {
        'form' : ProductoForm()
    }
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto registrado")
            
        else:
            data["form"] = formulario

    return render(request, 'app/producto/agregar.html', data)

@permission_required('app.view_producto')
def listar_productos(request):
    productos = Producto.objects.all()
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(productos, 10)
        productos = paginator.page(page)
    except:
        raise Http404

    data = {
        'entity' : productos,
        'paginator': paginator
    }
    return render(request, 'app/producto/listar.html', data)


def modificar_producto(request, id):
    
    producto = get_object_or_404(Producto, id=id)

    data = {
        'form': ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Se modifico correctamente")
            data["mensaje"] = "modificado correctamente"
            return redirect(to="home")
        data["form"] = formulario
    return render(request, 'app/producto/modificar.html', data)


def eliminar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    messages.success(request, "Se elimino corectamente")
    return redirect(to="home")

def registro(request):
    data = {
        'form': CustomUserCreationFrom()
    }
    if request.method == 'POST':
        formulario = CustomUserCreationFrom(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, "Te has registrado correctamente")
            #refirigir al home
            return redirect(to="home")
        data["form"] = formulario
    return render(request, 'registration/registro.html', data)
 

APP_ANUNCIOS/app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IKLAN</title>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap" rel="stylesheet">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    {% block css %} 
    {% endblock %}
    <link rel="stylesheet" href="{% static 'app/css/estilos.css' %}">
    {% load pwa %}
    {% progressive_web_app_meta %}
    
</head>
<body>
    <div>
            <nav id="nav">
                <ul>
                    <img  class="logo"  src="{% static 'app/img/logo.png' %}" alt="logo">

                    <li><a href="{% url 'home' %}">Inicio</a></li>
                    <li><a href="{% url 'home' %}"> Categoria</a>
                        <ul>
                            {% for c in categorias %}
                            <li><a href="{% url 'cat' c.id %}" >{{ c.nombre }}</a>
                            {% endfor %}
                        </ul>
                    </li>

                    {% if user.is_authenticated  %}

                    <li><a href="">Anuncios</a>
                        <ul>
                            <li><a href="{% url 'agregar_producto' %}">Agregar Anuncios</a></li>
                            
                            {% if perms.app.view_producto %}
                            <li><a href="{% url 'listar_productos' %}">Listado de Anuncios</a></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                    </li>
                    
                    
                    <li id="logoper">{% if user.is_authenticated  %}
                        <img id="logoper" src="{% static 'app/img/persona.ico'%}" alt="persona1" >
                        <ul>
                            
                            <li><a href="#">{{ user.username }}</a>
                            <li><a href="{% url 'logout' %}">Cerrar sesion</a></li>
                            {% if perms.app.view_producto %}
                            <li><a href="http://localhost:8000/admin/">Admin</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    <li>
                        {% for auth in backends.associated %}
                            {% if auth.provider == 'facebook' %}
                                <img src="{{ auth.extra_data.picture.data.url }}" alt="" width="50" height="50">
                            {% endif %}
                        {% endfor %}
                    </li>
                    {% else %}
                    <li>
                        <img src="{% static 'app/img/persona.ico'%}" alt="persona2">
                        <ul>
                            <li><a href="{% url 'login' %}">Iniciar sesion</a></li>
                            <li><a href="{% url 'registro' %}">Registrate</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
            </nav>
    </div>    
     
    <div id="contenido">
<br><br><br><br><br><br>
        {% block contenido %}
        {% endblock %}

    </div>

    <br><br><br>
    <footer>
        <div class="footer"><br>
            <div class="redes">
                <a href="https://www.facebook.com/IKLAN-1907327069553206/?ref=pages_you_manage"><img src="{% static 'app/img/facebook.ico'%}" alt="facebook"><b> Facebook</b></a><br><br>
                <a href="https://instagram.com/iklan_anuncios?utm_medium=copy_link"><img src="{% static 'app/img/instagram.ico'%}" alt=""><b> Instagram</b></a><br><br>
                <a href="https://wa.link/m8yp4o"><img src="{% static 'app/img/whatsapp.ico'%}" alt=""><b> WhatApp</b></a>
            </div>
            <div class="terminos"><br><br><br>
               <h3><a href="{% url 'terminos' %}"><b>Terminos y Condiciones</b></a></h3> 
               <h6>&#9400 2021 Iklan_anuncios</h6>
            </div>
            <div class="contactanos">
                <h4><b>CONTACTANOS</b></h4>
                <a href="https://wa.link/t3r2k7"><b>3127463573</b></a><br><br>
                <a href="https://wa.link/m8yp4o"><b>3146745331</b></a>
            </div>

        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
    
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% block mesajeria %}
        {% if messages %}
            {% for m in messages %}
                <script>
                    Swal.fire({
                        "title": "Felicitaciones",
                        "text": "{{m}}",
                        "icon": "success"
                    })
                </script>
            {% endfor %}
        {% endif %}
    {% endblock %}
    {% block js %} 
    {% endblock %}

</body>
</html>

APP_ANUNCIOS/app/templates/app/cat.html
{% extends 'app/base.html' %}

{% load static %} 

{% block js %} 
<script>
    function eliminarProducto(id) {
        Swal.fire({
            "title": "¿Estas seguro?",
            "text":"Esta acción no se puede deshacer",
            "icon": "question",
            "showCancelButton":true,
            "cancelButtonText":"No, Cancelar",
            "confirmButtonText":"Si, Eliminar",
            "reverseButtons":true,
            "confirmButtonColor":"#dc3545"
        })
        .then(function(result) {
            if(result.isConfirmed){
                window.location.href = "/eliminar-producto/"+id+"/"
            }
        })
    }
</script>

<script src="{% static 'app/js/menu.js' %}"></script>
<script>
    $(document).ready(function() {
      $('.slider').bxSlider({
          mode: 'fade',//horizontal, vertical, fade
          auto: true,
          pause: 2000
      });   
    });
</script>

{% endblock %}

{% block css %} 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
{% endblock %}

{% block contenido %} 



{% load humanize %}
<h1>{{ c.nombre }}</h1>
<div class="anuncios">    
    <ul>
   
        {% for p in productos %}
        <li>
            {% if p.imagen %}
            <img src="{{ p.imagen.url }}" alt="imagen producto">
            {% endif %}
            <div class="info">
                <h4>{{ p.nombre | title }}</h4>
                <h6>{{ p.descripción }}</h6> 
                <h6>{{ p.fecha_fabricacion }}</h6>
                <a href="https://wa.link/m8yp4o"><img src="{% static 'app/img/whatsapp2.ico'%}" alt="whatsapp"><b> Comprar</b></a><br>

                {% if user.username == p.username%}
                {% if user.is_authenticated %}
                <a href="{% url 'modificar_producto' p.id %}"><img src="{% static 'app/img/editar.ico'%}"></a>
                {% endif %}
                {% if user.is_authenticated %}
                <a href="#" onclick="eliminarProducto({{ p.id }})"><img  src="{% static 'app/img/eliminar.ico'%}"></a> 
                {% endif %}
                {% endif %}
            </div>
            </li>
            {% endfor %}
        </ul>
    

</div>

{% endblock %}

APP_ANUNCIOS/app/templates/app/contacto.html
{% extends 'app/base.html' %} 

{% block contenido %}
{% load crispy_forms_tags %}

<body id="imagenFormularios">
<br>
<br>
<div class="row">
    <div class="col-8 col-md-5 offset-md-4">
        <div class="cardContacto">
            <div class="card-body">
         
                <h2 id="LosFormularios">Contactenos</h2>
              
                <br>
                <hr>
                <form action="" class="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
             
                    <br>
                    <div class="conEnviar">
                        <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
                        &nbsp;                            
                    </div>
                    <br>
                    <div class="conCancelar">                        
                        <input type="reset" value="Cancelar" class="btn btn-secondary">                 
                    </div>
                    
        
                </form>    
                {{mensaje}}                
            </div>
        </div>
    </div>
</div>
<br>
<br>
</body>

<table id="tablacontactos">
    
</table>
{% endblock %}

APP_ANUNCIOS/app/templates/app/galeria.html
{% extends 'app/base.html' %} 
{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>

{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}

{% block contenido %} 

<br>
<h1 id=>Nuestras sedes</h1>
           <br><br>
           <div class="sedes">
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda1.jpeg' %}"><img src="{% static 'app/img/tienda/tienda1.jpeg' %}"></a>
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda2.jpeg' %}"><img src="{% static 'app/img/tienda/tienda2.jpeg' %}"></a>
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda3.jpeg' %}"><img src="{% static 'app/img/tienda/tienda3.jpeg' %}"></a>
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda4.jpeg' %}"><img src="{% static 'app/img/tienda/tienda4.jpeg' %}"></a>
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda5.jpeg' %}"><img src="{% static 'app/img/tienda/tienda5.jpeg' %}"></a>
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda6.jpeg' %}"><img src="{% static 'app/img/tienda/tienda6.jpeg' %}"></a>  
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda7.jpeg' %}"><img src="{% static 'app/img/tienda/tienda7.jpeg' %}"></a>  
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda8.jpeg' %}"><img src="{% static 'app/img/tienda/tienda8.jpeg' %}"></a>
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda9.jpeg' %}"><img src="{% static 'app/img/tienda/tienda9.jpeg' %}"></a>
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda10.jpeg' %}"><img src="{% static 'app/img/tienda/tienda10.jpeg' %}"></a>  
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda11.jpeg' %}"><img src="{% static 'app/img/tienda/tienda11.jpeg' %}"></a>  
                <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda12.jpeg' %}"><img src="{% static 'app/img/tienda/tienda12.jpeg' %}"></a>  
           </div>

{% endblock %}

APP_ANUNCIOS/app/templates/app/home.html
{% extends 'app/base.html' %}

{% load static %} 

{% block js %}
<script>
    function eliminarProducto(id) {
        Swal.fire({
            "title": "¿Estas seguro?",
            "text":"Esta acción no se puede deshacer",
            "icon": "question",
            "showCancelButton":true,
            "cancelButtonText":"No, Cancelar",
            "confirmButtonText":"Si, Eliminar",
            "reverseButtons":true,
            "confirmButtonColor":"#dc3545"
        })
        .then(function(result) {
            if(result.isConfirmed){
                window.location.href = "/eliminar-producto/"+id+"/"
            }
        })
    }
</script>
<script src="{% static 'app/js/menu.js' %}"></script>
<script>
    $(document).ready(function() {
      $('.slider').bxSlider({
          mode: 'fade',//horizontal, vertical, fade
          auto: true,
          pause: 2000
      });
    });
</script>
{% endblock %}

{% block css %} 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
{% endblock %}

{% block contenido %} 

<br>
<div class="slider">
    <div>
        <img src="{% static 'app/img/banner/banner.jpg' %}" alt="">
    </div>
    <div>
        <img src="{% static 'app/img/banner/banner2.jpg' %}" alt="">
    </div>
    <div>
        <img src="{% static 'app/img/banner/banner3.jpg' %}" alt="">
    </div>
    <div>
        <img src="{% static 'app/img/banner/banner4.jpg' %}" alt="">
    </div>
</div>
{% load humanize %}
<h1>ANUNCIOS</h1>
<div class="anuncios">    
    <ul>
   
        {% for p in productos %}
        <li>
            {% if p.imagen %}
            <img src="{{ p.imagen.url }}" alt="imagen producto">
            {% endif %}
            <div class="info">
                <h4 id="nombreAnuncios">{{ p.nombre | title }}</h4>
                <h6>{{ p.descripción }}</h6> 
                <h6>{{ p.fecha_fabricacion }}</h6>
                <a href="https://wa.link/m8yp4o"><img src="{% static 'app/img/whatsapp2.ico'%}" alt="whatsapp"><b> Comprar</b></a><br>

                {% if user.username == p.username%}
                {% if user.is_authenticated %}
                <a href="{% url 'modificar_producto' p.id %}"><img src="{% static 'app/img/editar.ico'%}"></a>
                {% endif %}
                {% if perms.app.delete_producto %}
                <a href="#" onclick="eliminarProducto({{ p.id }})"><img src="../static/app/img/eliminar.ico"></a> 
                {% endif %}
                {% endif %}
            </div>
            </li>
            {% endfor %}
        </ul>
    

</div>

{% endblock %}

APP_ANUNCIOS/app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

APP_ANUNCIOS/app/templates/app/producto/agregar.html
{% extends 'app/base.html' %}

{% block contenido %} 


{% load crispy_forms_tags %}
<body id="imagenFormularios">

        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="cardProductoNuevo">    
                    <div class="card-body">
                        <h2 id="LosFormularios">Nuevo Anuncio</h2>
                        <hr>
                        <form action="" method="post" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form | crispy }}
                            
                            <br>
                                <div class="productoNuevo">
                                    <input type="submit" value="Guardar" class="btn btn-primary-Guardar">
                                </div>
                                <br>                        
                                <div class="cancelarProducto">
                                  <input type="reset" value="Cancelar" class="btn btn-secondary-Cancelar" >
                                    &nbsp;
                                </div>
                    </form>
                    {{mensaje}}

            </div>
        </div>
        <br><br>
    </div>
</div>
</body>

{% endblock %}

APP_ANUNCIOS/app/templates/app/producto/listar.html
{% extends 'app/base.html' %}

{% block js %}

<script>
    function eliminarProducto(id) {
        Swal.fire({
            "title": "¿Estas seguro?",
            "text":"Esta acción no se puede deshacer",
            "icon": "question",
            "showCancelButton":true,
            "cancelButtonText":"No, Cancelar",
            "confirmButtonText":"Si, Eliminar",
            "reverseButtons":true,
            "confirmButtonColor":"#dc3545"
        })
        .then(function(result) {
            if(result.isConfirmed){
                window.location.href = "/eliminar-producto/"+id+"/"
            }
        })
    }
</script>
   
{% endblock %}

{% block contenido %} 
{% load humanize %}
<body id="imagenFormularios">

<div class="cardListado">
    <div class="card-body">

            <h2 id="LosFormularios">Listado de Anuncios</h2>       

        <table class="table table-striped table-hover table-responsive-sm">
            <tr id="listaProducto">
                <hr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Marca</th>
                <th>Importado</th>
                <th>Opciones</th>
            </tr>
        
            {% for p in entity %}
        
            <tr>
                <td>{{ p.nombre | title }}</td>
                <td>${{ p.precio | intcomma }}</td>
                <td>{{ p.marca | title }}</td>
                <td>
                    {% if p.nuevo %}
                    SI
                    {% else %}
                    NO
                    {% endif %}
                </td>
                <td>
                    {% if perms.app.change_producto %}
                    <a href="{% url 'modificar_producto' p.id %}"><img src="../static/app/img/editar.ico"></a>
                    {% endif %}
                    {% if perms.app.delete_producto %}
                    <a href="#" onclick="eliminarProducto({{ p.id }})"><img src="../static/app/img/eliminar.ico"></a> 
                    {% endif %}
                </td>
            </tr>
          
        
            {% endfor %}
        
        </table>
        <hr>
        <div>
            {% include 'app/paginator.html'  %}
        </div>
    </div>
</div>
<br><br>
</body>
{% endblock %}

APP_ANUNCIOS/app/templates/app/producto/modificar.html
{% extends 'app/base.html' %}

{% block contenido %} 


{% load crispy_forms_tags %}
<body id="imagenFormularios">
<br><br>
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="cardModificar">    
                    <div class="card-body">
                        <h2 id="LosFormularios">Editar producto</h2>
                        <hr>
                        <form action="" method="post" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form | crispy }}

                            <br>
                            <div class="modificarProducto">
                                <input type="submit" value="Editar" class="btn btn-primary-modificar-guar">
                            </div>

                            <br>

                            <div class="canceModifiProducto">
                                <input type="reset" value="Cancelar" class="btn btn-secondary-modificas-cance" >
                                &nbsp;
                            </div>
                            

                    </form>
                    {{mensaje}}

                    </div>
                </div>
            </div>
        </div>
        <br><br>
</body>

{% endblock %}

APP_ANUNCIOS/app/templates/offline.html
{% extends 'app/base.html' %}

{% block contenido %}

<h2>No tienes internet, favor revisa tu conexión</h2>

{% endblock %}